//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Role_Menu_MVC
{
    using System;
    
    public partial class RoleUser
    {
        public Nullable<int> UserId { get; set; }
        public string Roles { get; set; }
    }
}
